class QoryName:
    name_qory = [
        "Nafi' Al Madani",
        "Ashim Al Kufi",
        "Ali Al Kisay Al Kufi",
        "Ibnu Katsir Al Makki",
        "Abu Amru Al Bashri",
        "Ibnu Amir Asy Syami",
        "Hamzah Az Zayyat Al Kufi",
        "Asy Syatibi",
        "Al Jazari"
    ]
    
    name_surah = [
        "1. Al Faatihah",
        "2. Al Baqarah",
        "3. Ali Imran",
        "4. An Nisa",
        "5. Al Maidah",
        "6. Al An'am",
        "7. Al A'raf",
        "8. Al Anfal",
        "9. At Taubah",
        "10. Yunus",
        "11. Hud",
        "12. Yusuf",
        "13. Ar Ra'd",
        "14. Ibrahim",
        "15. Al Hijr",
        "16. An Nahl",
        "17. Al Isra",
        "18. Al Kahfi",
        "19. Maryam",
        "20. Thaahaa",
        "21. Al Anbiya",
        "22. Al Hajj",
        "23. Al Mu'minun",
        "24. An Nuur",
        "25. Al Furqaan",
        "26. Asy Syuaraa",
        "27. An Naml",
        "28. Al Qashash",
        "29. Al Ankabuut",
        "30. Ar Ruum",
        "31. Luqmaan",
        "32. As Sajadah",
        "33. Al Ahzaab",
        "34. Sabaa",
        "35. Fathir",
        "36. Yasiin",
        "37. Ash Shoffat",
        "38. Shaad",
        "39. Az Zumar",
        "40. Ghoofir",
        "41. Fushshilat",
        "42. Asy Syuura",
        "43. Az Zuhruf",
        "44. Ad Dukhaan",
        "45. Al Jaatsiyah",
        "46. Al Ahqaaf",
        "47. Muhammad",
        "48. Al Fath",
        "49. Al Hujuraat",
        "50. Qaaf",
        "51. Ads Dsaariyaat",
        "52. Ath Thuur",
        "53. An Najm",
        "54. Al Qamar",
        "55. Ar Rahman",
        "56. Al Wakiah",
        "57. Al Hadiid",
        "58. Al Mujaadalah",
        "59. Al Hasyr",
        "60. Al Mumtahanah",
        "61. Ash Shaaf",
        "62. Al Jumuah",
        "63. Al Munaafikuun",
        "64. Ath Thagaabun",
        "65. Ath Thalaaq",
        "66. At Tahrim",
        "67. Al Mulk",
        "68. Al Qalam",
        "69. Al Haqqah",
        "70. Al Maarij",
        "71. Nuuh",
        "72. Al Jin",
        "73. Al Muzammil",
        "74. Al Muddatstsir",
        "75. Al Qiyamah",
        "76. Al Insaan",
        "77. Al Mursalat",
        "78. An Nabaa",
        "79. An Naaziaat",
        "80. Abasa",
        "81. At Takwiir",
        "82. Al Infithaar",
        "83. Al Muthaffifin",
        "84. Al Insyiqaaq",
        "85. Al Buruuj",
        "86. Ath Thaariq",
        "87. Al A'laa",
        "88. Al Ghasyiyah",
        "89. Al Fajr",
        "90. Al Balad",
        "91. Asy Syams",
        "92. Al Lail",
        "93. Adh Dhuhaa",
        "94. Asy Syarah",
        "95. At Tiin",
        "96. Al Alaq",
        "97. Al Qadr",
        "98. Al Bayyinah",
        "99. Az Zalzilah",
        "100. Al Aadiyaat",
        "101. Al Qaariah",
        "102. At Takaatsur",
        "103. Al Ashar",
        "104. Al Humazah",
        "105. Al Fiil",
        "106. Quraisy",
        "107. Al Maaun",
        "108. Al Kautsar",
        "109. Al Kaafiruun",
        "110. An Nashr",
        "111. Al Masaad",
        "112. Al Ikhlaash",
        "113. Al Falaq",
        "114. An Naas"
    ]
    
    warsy_text = """[color=#aaaa00][size=22][b]MUSHAF IMAM[/b][/size][/color]
    
    [color=#000033][size=20]WARSY Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend, urna at semper iaculis, lacus augue fermentum nisi, vel finibus eros metus a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu feugiat metus. Nam nibh arcu, egestas at bibendum nec, consequat vel sapien. Phasellus vitae bibendum ex. Phasellus in pretium ligula. Nulla tristique, justo ut rutrum vehicula, orci dolor cursus leo, efficitur suscipit quam massa id enim. In varius purus et tellus tincidunt, et iaculis diam varius. Nam sapien lorem, rutrum non hendrerit ac, faucibus in lacus. Ut pretium diam in tortor accumsan eleifend. Phasellus sit amet nibh quis ex posuere rutrum sed quis tortor. Maecenas finibus faucibus felis sit amet ornare. 
    
        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.     
           
        Ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend, urna at semper iaculis, lacus augue fermentum nisi, vel finibus eros metus a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu feugiat metus. Nam nibh arcu, egestas at bibendum nec, consequat vel sapien. Phasellus vitae bibendum ex. Phasellus in pretium ligula. Nulla tristique, justo ut rutrum vehicula, orci dolor cursus leo, efficitur suscipit quam massa id enim. In varius purus et tellus tincidunt, et iaculis diam varius. Nam sapien lorem, rutrum non hendrerit ac, faucibus in lacus. Ut pretium diam in tortor accumsan eleifend. Phasellus sit amet nibh quis ex posuere rutrum sed quis tortor. Maecenas finibus faucibus felis sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
        
        posuere lectus vel lectus convallis facilisis. Aliquam quis sem sed magna imperdiet pulvinar. Curabitur ipsum nulla, pharetra vitae scelerisque vel, iaculis tincidunt felis. Nunc accumsan, velit egestas ullamcorper sollicitudin, ipsum orci semper felis, sed congue diam libero nec magna. Aenean id tellus ut massa blandit facilisis ultricies eleifend augue. Nulla ac mi nec nulla interdum semper. Etiam cursus tortor quam. Sed vehicula, justo non tempus efficitur, velit nibh viverra velit, molestie fermentum nulla augue eu erat. Curabitur tristique ut nibh semper efficitur. Aenean semper fringilla facilisis. Vivamus lobortis, massa eu ultrices egestas, eros nulla pretium sapien, vitae porttitor neque lacus quis sem. Vivamus id vehicula purus, id vulputate quam. Nunc auctor cursus urna, eu tempus urna viverra in. Suspendisse accumsan lorem urna, a porta dui tincidunt sit amet. Curabitur nec fringilla lorem, ac cursus odio.

            Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

            Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

            Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.

        Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

        Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

        Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.
        
        
        
        .[/size][/color]"""
    
    qolun_text = """[color=#0000ff][size=22][b]KAIDAH IMAM[/b][/size][/color] 
    
    [size=20]QOLUN Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend, urna at semper iaculis, lacus augue fermentum nisi, vel finibus eros metus a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu feugiat metus. Nam nibh arcu, egestas at bibendum nec, consequat vel sapien. Phasellus vitae bibendum ex. Phasellus in pretium ligula. Nulla tristique, justo ut rutrum vehicula, orci dolor cursus leo, efficitur suscipit quam massa id enim. In varius purus et tellus tincidunt, et iaculis diam varius. Nam sapien lorem, rutrum non hendrerit ac, faucibus in lacus. Ut pretium diam in tortor accumsan eleifend. Phasellus sit amet nibh quis ex posuere rutrum sed quis tortor. Maecenas finibus faucibus felis sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

        Integer posuere lectus vel lectus convallis facilisis. Aliquam quis sem sed magna imperdiet pulvinar. Curabitur ipsum nulla, pharetra vitae scelerisque vel, iaculis tincidunt felis. Nunc accumsan, velit egestas ullamcorper sollicitudin, ipsum orci semper felis, sed congue diam libero nec magna. Aenean id tellus ut massa blandit facilisis ultricies eleifend augue. Nulla ac mi nec nulla interdum semper. Etiam cursus tortor quam. Sed vehicula, justo non tempus efficitur, velit nibh viverra velit, molestie fermentum nulla augue eu erat. Curabitur tristique ut nibh semper efficitur. Aenean semper fringilla facilisis. Vivamus lobortis, massa eu ultrices egestas, eros nulla pretium sapien, vitae porttitor neque lacus quis sem. Vivamus id vehicula purus, id vulputate quam. Nunc auctor cursus urna, eu tempus urna viverra in. Suspendisse accumsan lorem urna, a porta dui tincidunt sit amet. Curabitur nec fringilla lorem, ac cursus odio.

        Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

        Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

        Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.

        Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

        Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

        Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.[/size]"""

    hafs_text =  """[color=#ff0000][size=22][b]RIWAYAT IMAM[/b][/size][/color]
    
    [size=20]HAFS Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend, urna at semper iaculis, lacus augue fermentum nisi, vel finibus eros metus a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu feugiat metus. Nam nibh arcu, egestas at bibendum nec, consequat vel sapien. Phasellus vitae bibendum ex. Phasellus in pretium ligula. Nulla tristique, justo ut rutrum vehicula, orci dolor cursus leo, efficitur suscipit quam massa id enim. In varius purus et tellus tincidunt, et iaculis diam varius. Nam sapien lorem, rutrum non hendrerit ac, faucibus in lacus. Ut pretium diam in tortor accumsan eleifend. Phasellus sit amet nibh quis ex posuere rutrum sed quis tortor. Maecenas finibus faucibus felis sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

        Integer posuere lectus vel lectus convallis facilisis. Aliquam quis sem sed magna imperdiet pulvinar. Curabitur ipsum nulla, pharetra vitae scelerisque vel, iaculis tincidunt felis. Nunc accumsan, velit egestas ullamcorper sollicitudin, ipsum orci semper felis, sed congue diam libero nec magna. Aenean id tellus ut massa blandit facilisis ultricies eleifend augue. Nulla ac mi nec nulla interdum semper. Etiam cursus tortor quam. Sed vehicula, justo non tempus efficitur, velit nibh viverra velit, molestie fermentum nulla augue eu erat. Curabitur tristique ut nibh semper efficitur. Aenean semper fringilla facilisis. Vivamus lobortis, massa eu ultrices egestas, eros nulla pretium sapien, vitae porttitor neque lacus quis sem. Vivamus id vehicula purus, id vulputate quam. Nunc auctor cursus urna, eu tempus urna viverra in. Suspendisse accumsan lorem urna, a porta dui tincidunt sit amet. Curabitur nec fringilla lorem, ac cursus odio.

        Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

        Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

        Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.

        Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

        Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

        Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.[/size]"""

    syubah_text = """[color=#00aa00][size=22][b]TAJEWID IMAM[/b][/size][/color]
    
    [size=20]SYU'BAH Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend, urna at semper iaculis, lacus augue fermentum nisi, vel finibus eros metus a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu feugiat metus. Nam nibh arcu, egestas at bibendum nec, consequat vel sapien. Phasellus vitae bibendum ex. Phasellus in pretium ligula. Nulla tristique, justo ut rutrum vehicula, orci dolor cursus leo, efficitur suscipit quam massa id enim. In varius purus et tellus tincidunt, et iaculis diam varius. Nam sapien lorem, rutrum non hendrerit ac, faucibus in lacus. Ut pretium diam in tortor accumsan eleifend. Phasellus sit amet nibh quis ex posuere rutrum sed quis tortor. Maecenas finibus faucibus felis sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

        Integer posuere lectus vel lectus convallis facilisis. Aliquam quis sem sed magna imperdiet pulvinar. Curabitur ipsum nulla, pharetra vitae scelerisque vel, iaculis tincidunt felis. Nunc accumsan, velit egestas ullamcorper sollicitudin, ipsum orci semper felis, sed congue diam libero nec magna. Aenean id tellus ut massa blandit facilisis ultricies eleifend augue. Nulla ac mi nec nulla interdum semper. Etiam cursus tortor quam. Sed vehicula, justo non tempus efficitur, velit nibh viverra velit, molestie fermentum nulla augue eu erat. Curabitur tristique ut nibh semper efficitur. Aenean semper fringilla facilisis. Vivamus lobortis, massa eu ultrices egestas, eros nulla pretium sapien, vitae porttitor neque lacus quis sem. Vivamus id vehicula purus, id vulputate quam. Nunc auctor cursus urna, eu tempus urna viverra in. Suspendisse accumsan lorem urna, a porta dui tincidunt sit amet. Curabitur nec fringilla lorem, ac cursus odio.

        Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

        Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.[/size]"""

    abualharits_text = """ABU AL HARITS Mukhta-Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend, urna at semper iaculis, lacus augue fermentum nisi, vel finibus eros metus a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu feugiat metus. Nam nibh arcu, egestas at bibendum nec, consequat vel sapien. Phasellus vitae bibendum ex. Phasellus in pretium ligula. Nulla tristique, justo ut rutrum vehicula, orci dolor cursus leo, efficitur suscipit quam massa id enim. In varius purus et tellus tincidunt, et iaculis diam varius. Nam sapien lorem, rutrum non hendrerit ac, faucibus in lacus. Ut pretium diam in tortor accumsan eleifend. Phasellus sit amet nibh quis ex posuere rutrum sed quis tortor. Maecenas finibus faucibus felis sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.

Integer posuere lectus vel lectus convallis facilisis. Aliquam quis sem sed magna imperdiet pulvinar. Curabitur ipsum nulla, pharetra vitae scelerisque vel, iaculis tincidunt felis. Nunc accumsan, velit egestas ullamcorper sollicitudin, ipsum orci semper felis, sed congue diam libero nec magna. Aenean id tellus ut massa blandit facilisis ultricies eleifend augue. Nulla ac mi nec nulla interdum semper. Etiam cursus tortor quam. Sed vehicula, justo non tempus efficitur, velit nibh viverra velit, molestie fermentum nulla augue eu erat. Curabitur tristique ut nibh semper efficitur. Aenean semper fringilla facilisis. Vivamus lobortis, massa eu ultrices egestas, eros nulla pretium sapien, vitae porttitor neque lacus quis sem. Vivamus id vehicula purus, id vulputate quam. Nunc auctor cursus urna, eu tempus urna viverra in. Suspendisse accumsan lorem urna, a porta dui tincidunt sit amet. Curabitur nec fringilla lorem, ac cursus odio.

Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris."""

    adduuriyK_text = """AD DUURIY KISAIY Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend, urna at semper iaculis, lacus augue fermentum nisi, vel finibus eros metus a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu feugiat metus. Nam nibh arcu, egestas at bibendum nec, consequat vel sapien. Phasellus vitae bibendum ex. Phasellus in pretium ligula. Nulla tristique, justo ut rutrum vehicula, orci dolor cursus leo, efficitur suscipit quam massa id enim. In varius purus et tellus tincidunt, et iaculis diam varius. Nam sapien lorem, rutrum non hendrerit ac, faucibus in lacus. Ut pretium diam in tortor accumsan eleifend. Phasellus sit amet nibh quis ex posuere rutrum sed quis tortor. Maecenas finibus faucibus felis sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend, urna at semper iaculis, lacus augue fermentum nisi, vel finibus eros metus a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu feugiat metus. Nam nibh arcu, egestas at bibendum nec, consequat vel sapien. Phasellus vitae bibendum ex. Phasellus in pretium ligula. Nulla tristique, justo ut rutrum vehicula, orci dolor cursus leo, efficitur suscipit quam massa id enim. In varius purus et tellus tincidunt, et iaculis diam varius. Nam sapien lorem, rutrum non hendrerit ac, faucibus in lacus. Ut pretium diam in tortor accumsan eleifend. Phasellus sit amet nibh quis ex posuere rutrum sed quis tortor. Maecenas finibus faucibus felis sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Integer posuere lectus vel lectus convallis facilisis. Aliquam quis sem sed magna imperdiet pulvinar. Curabitur ipsum nulla, pharetra vitae scelerisque vel, iaculis tincidunt felis. Nunc accumsan, velit egestas ullamcorper sollicitudin, ipsum orci semper felis, sed congue diam libero nec magna. Aenean id tellus ut massa blandit facilisis ultricies eleifend augue. Nulla ac mi nec nulla interdum semper. Etiam cursus tortor quam. Sed vehicula, justo non tempus efficitur, velit nibh viverra velit, molestie fermentum nulla augue eu erat. Curabitur tristique ut nibh semper efficitur. Aenean semper fringilla facilisis. Vivamus lobortis, massa eu ultrices egestas, eros nulla pretium sapien, vitae porttitor neque lacus quis sem. Vivamus id vehicula purus, id vulputate quam. Nunc auctor cursus urna, eu tempus urna viverra in. Suspendisse accumsan lorem urna, a porta dui tincidunt sit amet. Curabitur nec fringilla lorem, ac cursus odio.

Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris."""
    
    assuusiy_text = """AS SUUSIY Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend, urna at semper iaculis, lacus augue fermentum nisi, vel finibus eros metus a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu feugiat metus. Nam nibh arcu, egestas at bibendum nec, consequat vel sapien. Phasellus vitae bibendum ex. Phasellus in pretium ligula. Nulla tristique, justo ut rutrum vehicula, orci dolor cursus leo, efficitur suscipit quam massa id enim. In varius purus et tellus tincidunt, et iaculis diam varius. Nam sapien lorem, rutrum non hendrerit ac, faucibus in lacus. Ut pretium diam in tortor accumsan eleifend. Phasellus sit amet nibh quis ex posuere rutrum sed quis tortor. Maecenas finibus faucibus felis sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Integer posuere lectus vel lectus convallis facilisis. Aliquam quis sem sed magna imperdiet pulvinar. Curabitur ipsum nulla, pharetra vitae scelerisque vel, iaculis tincidunt felis. Nunc accumsan, velit egestas ullamcorper sollicitudin, ipsum orci semper felis, sed congue diam libero nec magna. Aenean id tellus ut massa blandit facilisis ultricies eleifend augue. Nulla ac mi nec nulla interdum semper. Etiam cursus tortor quam. Sed vehicula, justo non tempus efficitur, velit nibh viverra velit, molestie fermentum nulla augue eu erat. Curabitur tristique ut nibh semper efficitur. Aenean semper fringilla facilisis. Vivamus lobortis, massa eu ultrices egestas, eros nulla pretium sapien, vitae porttitor neque lacus quis sem. Vivamus id vehicula purus, id vulputate quam. Nunc auctor cursus urna, eu tempus urna viverra in. Suspendisse accumsan lorem urna, a porta dui tincidunt sit amet. Curabitur nec fringilla lorem, ac cursus odio.

Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris."""

    adduuriyA_text = """AD DUURIY AMRU Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend, urna at semper iaculis, lacus augue fermentum nisi, vel finibus eros metus a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu feugiat metus. Nam nibh arcu, egestas at bibendum nec, consequat vel sapien. Phasellus vitae bibendum ex. Phasellus in pretium ligula. Nulla tristique, justo ut rutrum vehicula, orci dolor cursus leo, efficitur suscipit quam massa id enim. In varius purus et tellus tincidunt, et iaculis diam varius. Nam sapien lorem, rutrum non hendrerit ac, faucibus in lacus. Ut pretium diam in tortor accumsan eleifend. Phasellus sit amet nibh quis ex posuere rutrum sed quis tortor. Maecenas finibus faucibus felis sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Integer posuere lectus vel lectus convallis facilisis. Aliquam quis sem sed magna imperdiet pulvinar. Curabitur ipsum nulla, pharetra vitae scelerisque vel, iaculis tincidunt felis. Nunc accumsan, velit egestas ullamcorper sollicitudin, ipsum orci semper felis, sed congue diam libero nec magna. Aenean id tellus ut massa blandit facilisis ultricies eleifend augue. Nulla ac mi nec nulla interdum semper. Etiam cursus tortor quam. Sed vehicula, justo non tempus efficitur, velit nibh viverra velit, molestie fermentum nulla augue eu erat. Curabitur tristique ut nibh semper efficitur. Aenean semper fringilla facilisis. Vivamus lobortis, massa eu ultrices egestas, eros nulla pretium sapien, vitae porttitor neque lacus quis sem. Vivamus id vehicula purus, id vulputate quam. Nunc auctor cursus urna, eu tempus urna viverra in. Suspendisse accumsan lorem urna, a porta dui tincidunt sit amet. Curabitur nec fringilla lorem, ac cursus odio.

Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris."""

    hisyam_text = """HISYAM Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend, urna at semper iaculis, lacus augue fermentum nisi, vel finibus eros metus a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu feugiat metus. Nam nibh arcu, egestas at bibendum nec, consequat vel sapien. Phasellus vitae bibendum ex. Phasellus in pretium ligula. Nulla tristique, justo ut rutrum vehicula, orci dolor cursus leo, efficitur suscipit quam massa id enim. In varius purus et tellus tincidunt, et iaculis diam varius. Nam sapien lorem, rutrum non hendrerit ac, faucibus in lacus. Ut pretium diam in tortor accumsan eleifend. Phasellus sit amet nibh quis ex posuere rutrum sed quis tortor. Maecenas finibus faucibus felis sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Integer posuere lectus vel lectus convallis facilisis. Aliquam quis sem sed magna imperdiet pulvinar. Curabitur ipsum nulla, pharetra vitae scelerisque vel, iaculis tincidunt felis. Nunc accumsan, velit egestas ullamcorper sollicitudin, ipsum orci semper felis, sed congue diam libero nec magna. Aenean id tellus ut massa blandit facilisis ultricies eleifend augue. Nulla ac mi nec nulla interdum semper. Etiam cursus tortor quam. Sed vehicula, justo non tempus efficitur, velit nibh viverra velit, molestie fermentum nulla augue eu erat. Curabitur tristique ut nibh semper efficitur. Aenean semper fringilla facilisis. Vivamus lobortis, massa eu ultrices egestas, eros nulla pretium sapien, vitae porttitor neque lacus quis sem. Vivamus id vehicula purus, id vulputate quam. Nunc auctor cursus urna, eu tempus urna viverra in. Suspendisse accumsan lorem urna, a porta dui tincidunt sit amet. Curabitur nec fringilla lorem, ac cursus odio.

Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris."""

    ibnudzakwan_text = """IBNU DZAKWAN-Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend, urna at semper iaculis, lacus augue fermentum nisi, vel finibus eros metus a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu feugiat metus. Nam nibh arcu, egestas at bibendum nec, consequat vel sapien. Phasellus vitae bibendum ex. Phasellus in pretium ligula. Nulla tristique, justo ut rutrum vehicula, orci dolor cursus leo, efficitur suscipit quam massa id enim. In varius purus et tellus tincidunt, et iaculis diam varius. Nam sapien lorem, rutrum non hendrerit ac, faucibus in lacus. Ut pretium diam in tortor accumsan eleifend. Phasellus sit amet nibh quis ex posuere rutrum sed quis tortor. Maecenas finibus faucibus felis sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.

Integer posuere lectus vel lectus convallis facilisis. Aliquam quis sem sed magna imperdiet pulvinar. Curabitur ipsum nulla, pharetra vitae scelerisque vel, iaculis tincidunt felis. Nunc accumsan, velit egestas ullamcorper sollicitudin, ipsum orci semper felis, sed congue diam libero nec magna. Aenean id tellus ut massa blandit facilisis ultricies eleifend augue. Nulla ac mi nec nulla interdum semper. Etiam cursus tortor quam. Sed vehicula, justo non tempus efficitur, velit nibh viverra velit, molestie fermentum nulla augue eu erat. Curabitur tristique ut nibh semper efficitur. Aenean semper fringilla facilisis. Vivamus lobortis, massa eu ultrices egestas, eros nulla pretium sapien, vitae porttitor neque lacus quis sem. Vivamus id vehicula purus, id vulputate quam. Nunc auctor cursus urna, eu tempus urna viverra in. Suspendisse accumsan lorem urna, a porta dui tincidunt sit amet. Curabitur nec fringilla lorem, ac cursus odio.

Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris."""

    qunbul_text = """QUNBUL Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend, urna at semper iaculis, lacus augue fermentum nisi, vel finibus eros metus a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu feugiat metus. Nam nibh arcu, egestas at bibendum nec, consequat vel sapien. Phasellus vitae bibendum ex. Phasellus in pretium ligula. Nulla tristique, justo ut rutrum vehicula, orci dolor cursus leo, efficitur suscipit quam massa id enim. In varius purus et tellus tincidunt, et iaculis diam varius. Nam sapien lorem, rutrum non hendrerit ac, faucibus in lacus. Ut pretium diam in tortor accumsan eleifend. Phasellus sit amet nibh quis ex posuere rutrum sed quis tortor. Maecenas finibus faucibus felis sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Integer posuere lectus vel lectus convallis facilisis. Aliquam quis sem sed magna imperdiet pulvinar. Curabitur ipsum nulla, pharetra vitae scelerisque vel, iaculis tincidunt felis. Nunc accumsan, velit egestas ullamcorper sollicitudin, ipsum orci semper felis, sed congue diam libero nec magna. Aenean id tellus ut massa blandit facilisis ultricies eleifend augue. Nulla ac mi nec nulla interdum semper. Etiam cursus tortor quam. Sed vehicula, justo non tempus efficitur, velit nibh viverra velit, molestie fermentum nulla augue eu erat. Curabitur tristique ut nibh semper efficitur. Aenean semper fringilla facilisis. Vivamus lobortis, massa eu ultrices egestas, eros nulla pretium sapien, vitae porttitor neque lacus quis sem. Vivamus id vehicula purus, id vulputate quam. Nunc auctor cursus urna, eu tempus urna viverra in. Suspendisse accumsan lorem urna, a porta dui tincidunt sit amet. Curabitur nec fringilla lorem, ac cursus odio.

Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris."""

    albazziy_text = """AL BAZZIY Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend, urna at semper iaculis, lacus augue fermentum nisi, vel finibus eros metus a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu feugiat metus. Nam nibh arcu, egestas at bibendum nec, consequat vel sapien. Phasellus vitae bibendum ex. Phasellus in pretium ligula. Nulla tristique, justo ut rutrum vehicula, orci dolor cursus leo, efficitur suscipit quam massa id enim. In varius purus et tellus tincidunt, et iaculis diam varius. Nam sapien lorem, rutrum non hendrerit ac, faucibus in lacus. Ut pretium diam in tortor accumsan eleifend. Phasellus sit amet nibh quis ex posuere rutrum sed quis tortor. Maecenas finibus faucibus felis sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Integer posuere lectus vel lectus convallis facilisis. Aliquam quis sem sed magna imperdiet pulvinar. Curabitur ipsum nulla, pharetra vitae scelerisque vel, iaculis tincidunt felis. Nunc accumsan, velit egestas ullamcorper sollicitudin, ipsum orci semper felis, sed congue diam libero nec magna. Aenean id tellus ut massa blandit facilisis ultricies eleifend augue. Nulla ac mi nec nulla interdum semper. Etiam cursus tortor quam. Sed vehicula, justo non tempus efficitur, velit nibh viverra velit, molestie fermentum nulla augue eu erat. Curabitur tristique ut nibh semper efficitur. Aenean semper fringilla facilisis. Vivamus lobortis, massa eu ultrices egestas, eros nulla pretium sapien, vitae porttitor neque lacus quis sem. Vivamus id vehicula purus, id vulputate quam. Nunc auctor cursus urna, eu tempus urna viverra in. Suspendisse accumsan lorem urna, a porta dui tincidunt sit amet. Curabitur nec fringilla lorem, ac cursus odio.

Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris."""

    khalaf_text = """ KHALAF Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend, urna at semper iaculis, lacus augue fermentum nisi, vel finibus eros metus a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu feugiat metus. Nam nibh arcu, egestas at bibendum nec, consequat vel sapien. Phasellus vitae bibendum ex. Phasellus in pretium ligula. Nulla tristique, justo ut rutrum vehicula, orci dolor cursus leo, efficitur suscipit quam massa id enim. In varius purus et tellus tincidunt, et iaculis diam varius. Nam sapien lorem, rutrum non hendrerit ac, faucibus in lacus. Ut pretium diam in tortor accumsan eleifend. Phasellus sit amet nibh quis ex posuere rutrum sed quis tortor. Maecenas finibus faucibus felis sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Integer posuere lectus vel lectus convallis facilisis. Aliquam quis sem sed magna imperdiet pulvinar. Curabitur ipsum nulla, pharetra vitae scelerisque vel, iaculis tincidunt felis. Nunc accumsan, velit egestas ullamcorper sollicitudin, ipsum orci semper felis, sed congue diam libero nec magna. Aenean id tellus ut massa blandit facilisis ultricies eleifend augue. Nulla ac mi nec nulla interdum semper. Etiam cursus tortor quam. Sed vehicula, justo non tempus efficitur, velit nibh viverra velit, molestie fermentum nulla augue eu erat. Curabitur tristique ut nibh semper efficitur. Aenean semper fringilla facilisis. Vivamus lobortis, massa eu ultrices egestas, eros nulla pretium sapien, vitae porttitor neque lacus quis sem. Vivamus id vehicula purus, id vulputate quam. Nunc auctor cursus urna, eu tempus urna viverra in. Suspendisse accumsan lorem urna, a porta dui tincidunt sit amet. Curabitur nec fringilla lorem, ac cursus odio.

Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris."""

    khallad_text = """KHALLAD Mukhta-Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend, urna at semper iaculis, lacus augue fermentum nisi, vel finibus eros metus a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu feugiat metus. Nam nibh arcu, egestas at bibendum nec, consequat vel sapien. Phasellus vitae bibendum ex. Phasellus in pretium ligula. Nulla tristique, justo ut rutrum vehicula, orci dolor cursus leo, efficitur suscipit quam massa id enim. In varius purus et tellus tincidunt, et iaculis diam varius. Nam sapien lorem, rutrum non hendrerit ac, faucibus in lacus. Ut pretium diam in tortor accumsan eleifend. Phasellus sit amet nibh quis ex posuere rutrum sed quis tortor. Maecenas finibus faucibus felis sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris.

Integer posuere lectus vel lectus convallis facilisis. Aliquam quis sem sed magna imperdiet pulvinar. Curabitur ipsum nulla, pharetra vitae scelerisque vel, iaculis tincidunt felis. Nunc accumsan, velit egestas ullamcorper sollicitudin, ipsum orci semper felis, sed congue diam libero nec magna. Aenean id tellus ut massa blandit facilisis ultricies eleifend augue. Nulla ac mi nec nulla interdum semper. Etiam cursus tortor quam. Sed vehicula, justo non tempus efficitur, velit nibh viverra velit, molestie fermentum nulla augue eu erat. Curabitur tristique ut nibh semper efficitur. Aenean semper fringilla facilisis. Vivamus lobortis, massa eu ultrices egestas, eros nulla pretium sapien, vitae porttitor neque lacus quis sem. Vivamus id vehicula purus, id vulputate quam. Nunc auctor cursus urna, eu tempus urna viverra in. Suspendisse accumsan lorem urna, a porta dui tincidunt sit amet. Curabitur nec fringilla lorem, ac cursus odio.

Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Sed quis eros volutpat, tincidunt sem vitae, vulputate diam. Nulla ut ex pellentesque, feugiat nisi vel, ornare lectus. Etiam dapibus est rutrum suscipit ultricies. Ut sit amet blandit neque. Ut rutrum velit sed vehicula placerat. Nulla ullamcorper ullamcorper mollis. Donec in nisl nec felis tristique consequat auctor nec augue.

Cras sed est a lacus gravida accumsan in vel libero. Proin dolor nunc, interdum nec venenatis sed, pretium et elit. Donec a ex porta, bibendum dolor quis, rutrum quam. Vivamus id mauris viverra, congue risus sit amet, tristique libero. Aenean a blandit mi, consequat ullamcorper ante. Suspendisse a eros id augue tristique lobortis vitae quis quam. Etiam quis eros id velit accumsan condimentum quis nec velit. Sed eget enim mi. Aenean metus lectus, faucibus vitae arcu sit amet, iaculis maximus tortor. Sed porttitor massa sed ipsum commodo, nec aliquam erat cursus. Curabitur ut tristique augue, nec bibendum eros. Morbi non tortor efficitur, fermentum eros quis, venenatis augue.

Etiam nibh turpis, euismod dapibus magna vel, iaculis pharetra lectus. Phasellus at ante facilisis, condimentum orci et, consequat augue. Aenean rhoncus fermentum risus, eu condimentum dui vestibulum vitae. Etiam vel arcu ante. Nullam efficitur tellus id augue ultrices ultrices. Aliquam laoreet aliquam neque non aliquam. Donec interdum felis in metus eleifend pharetra. Vestibulum non magna ultricies, pellentesque tortor ut, consequat metus. Nulla vestibulum dapibus placerat. Nam non vulputate magna, et scelerisque justo. Proin eu tincidunt mauris."""

    asysyatiby_text = """[color=#0000dd][size=22][b]BIOGRAFI IMAM ASY STATIBY[/b][/font][/color]

    [size=20]Dunia ilmu qiraat mengenal nama yang cukup masyhur, yakni Imam asy-Syatibi. Nama lengkapnya adalah al-Qasim bin Firruh (dalam bahasa Spanyol berarti besi) bin Khalaf bin Ahmad al-Raiyni al-Dharir (buta) asy-Syatibi al-Andalusi. Kuniyah-nya adalah Abul Qasim. Kata “asy-Syatibi” dinisbatkan kepada kota Xativa di Spanyol. Harap dibedakan dari asy-Syatibi yang bernama lengkap Abu Ishaq Ibrahim bin Musa—pakar maqashid syariah, w. 790 H.

    Ia termasuk ulama kreatif. Berkat inovasinya, para pengaji ilmu qira'at bisa lebih mudah mempelajari disiplin yang mereka tekuni. Karya paling monomental Imam asy-Syatibi adalah Hirz al-Amani wa Wajh al-Tahani fi al-Qira’at al-Sab’i atau yang lebih dikenal dengan Matan Syatibi.   Pada dasarnya pokok pemikiran Imam asy-Syatibi dapat digambarkan dalam karya-karyanya. Ia ibarat potret pemikirannya dalam mendukomentasikan ilmu qira’at Al-Qur’an. Oleh karena itu, untuk mengentahui pokok-pokok pemikiran asy-Syatibi dapat dilihat dari dua hal; teori penulisan ilmu qira’at dan rumusan-rumusan dalam ilmu qira’at.[/size]

[color=#0000ff][size=20][b]1. Teori penulisan ilmu Qira’at[/b][/font][/color]

    Penulisan teori ilmu qira’at yang berkembang sebelum asy-Syatibi menggunakan prasa berbentuk natsar bukan qashidah, sehingga bagi sebagian para penuntut ilmu hal ini dianggap sulit untuk dihafal sebab dalam setiap teori bacaan ada yang sama dan ada yang berbeda. Terlebih jika harus menisbatkan setiap bacaan kepada penukilnya.   Untuk memudahkan para penuntut ilmu untuk memahami dan menghafal teori ilmu Qira’at, Imam asy-Syatibi melakukan inovasi baru dalam penulisan ilmu qira’at yaitu menyusunnya dalam bentuk qashidah. Karya ini bernama “Hirz al-Amani wa Wajh al-Thahani fi al-Qira’at al-Sab’I” atau dikenal dengan “Matan asy-Syatibi”.

    Penyusunan kitab ini terinspirasi dari kitab “al-Taisir fi al-Qira’at al-Sab’I” karya Imam Abu Amr al-Dani (w. 444 H). Dia pun dalam sistematika pembahasannya mengikuti alur dan jalur yang disampaikan oleh al-Dani. Meskipun ada beberapa perbedaan antara al-Dani dan asy-Syatibi. Misalkan dalam durasi qashr dan mad, Imam asy-Syatibi membagi tiga; pendek dua harakat, tasawwuth empat harakat dan isyba’ enam harakat. Sementara al-Dani mengklasifikasi secara rinci; pendek dua harakat, fuwaiq al-Qashr tiga harakat, tawassuth empat harakat, fuwaiq al-Tawassuth lima harakat dan isyba’ enam harakat.   Meskipun asy-Syatibi keluar dari pakem al-Dani dalam beberapa persoalan dan secara tegas asy-Syatibi menyatakan bahwa dalam kitab ini banyak tambahan-tambahan yang tidak ada dalam karya al-Dani, namun Imam asy-Syatibi dengan rasa ta’dhim dan sifat tawadhu’ menisbatkan karyanya ini sebagai ringkasan dari kitab “al-Taisir”, yang tidak bisa menandingi dan menyamakannya dengan karya al-Dani di atas.

    Hal ini dia sampaikan lewat gubahan qashidahnya:   وَفي يُسْرِهَا التَّيْسِيرُ رُمْتُ اخْتَصَارَهُ *** فَأَجْنَتْ بِعَوْنِ اللهِ مِنْهُ مُؤَمَّلَا وَأَلْفَافُهَا زَادَتْ بِنَشْرِ فَوَائِدٍ *** فَلَفَّتْ حَيَاءً وَجْهَهَا أَنْ تُفَضَّلَا   
    
    Artinya:
        
    [i][color=#880000]“Saya bermaksud dalam qashidah ini meringkas dari kitab “al-Taisir” dan menambah beberapa masalah dalam kitab tersebut seraya memohon pertolongan kepada Allah Swt,.   Dalam qashidah ini lebih lengkap daripada al-Taisir dalam beberapa keterangan yang tidak dijumpai dalam al-Taisir, karena ada beberapa keterangan tambahan seperti makharij huruf. Meskipun demikian, kitab ini tidak mampu menandingi keutamaan kitab al-Taisir. Ibaratnya, ini merupakan etika seorang anak kecil kepada orang dewasa, etika murid dengan gurunya, orang yang datang belakangan kepada orang yang lebih dahulu yang memiliki keutamaan, dan kitab ushul dibandingkan kitab fuur’.”.[/color][/i]

    Kitab ini membahas tentang tujuh ragam qira’at Al-Qur’an mutawatir, yaitu Imam Nafi’, Ibnu Katsir, Abu Amr, Ibnu Amir, Ashim, Hamzah dan Ali al-Kisa’I. Pemhabasan kitab ini sangat sistematis, padat dan berisi sehingga tidak menjemukan bagi para pengkajinya. Sebab asy-Syatibi mampu menggubah kajian ilmu qira’at yang semula dianggap sulit ke dalam bait-bait syair yang sangat indah berestetika dengan menggunakan bahar Thawil (notasi bait syair-syair Arab). Semakin indah bait syair ini dengan balutan qafiyah (akhiran) “La”. Makanya ulama menyebut istilah kitab ini dengan “Qasidah al-Lamiyah”.

    Banyaknya perbedaan dan penisbatan bacaan yang ada dalam ilmu qira’at mampu diringkas oleh asy-Syatibi dalam jumlah 1173.   Sistematika kitab ini secara singkat ada dua poin penting; muqaddimah, yang mencakup ushul qira’at yang berjumlah 444. Penulis (red; saya) berpendapat, bahwa angka 444 ini bukan kebetulan belaka tapi ada rahasia di balik itu, yaitu untuk mengingat tahun wafatnya Imam al-Dani, sang inspirator karya ini. Dalam mengingat terdapat untaian doa yang dipanjatkan untuk sang inspirator, dalam penyebutan terdapat keta’dziman dan penghargaan setinggi-tingginya.   

    Dalam muqaddimah (kata pengantar) nya terdapat 94 bait qashidah, yanng mencakup pujian kepada Allah dan Nabi-Nya, penyebutan nama-nama para qurra’ dan perawinya, kemudian menjelaskan tentang rumus-rumus dalam memahami nama-nama imam qira’at, baik dalam bentuk sendirian maupun dalam bentuk bersama. Selanjutnya menjelaskan tentang istilah-istilah dalam qashidah dilanjutkan dengan pembahasan Isti’adzah, basmalah, ummul Qur’an, idgham kabir, ha’ kinayah dan lain-lain.   Sementara sisanya 729 adalah fokus pada pembahasan furusy al-Qira’at, yang dimulai dari surat al-Baqarah hingga al-Nas. Yang menarik adalah asy-Syatibi menempatkan ummul qur’an atau surat al-Fatihah ditaruh di bab Ushul Qira’at. Hal ini tidak lain adalah mengikuti sesuai sistematika kitab asal-nya, yaitu al-Taisir. Meskipun seharusnya ia ditempatkan di bab Ushul a-Qira’at. Sebaliknya, bab Takbir--makkiyin-- dan makharij huruf ditaruh diakhir bab setelah furusy al-Qira’at.   Kitab ini mendapat perhatian yang sangat besar dari ulama sesudahnya sehingga banyak yang memberi komentar atau mensyarah kitab ini. Di sini penulis akan petekan sebagian dari syarah-syarah kitab tersebut;

[color=#880000][i]1. Fathul Washid karya imam Alamuddin al-Sakhawi 

2. Kanzul Ma’ani Syarh Hirz al-Amani karya 
   Muhammad al-Mushili yang dikenal dengan 
   panggilan “Sya’lah”

3. Ibraz al-Ma’ani min Hirz al-Amani karya Abu
   Syamah 

4. Kanzul Ma’ani karya al-Ja’bari

5. Siraj al-Qari’ karya Ibnu al-Qashih

6. Al-Wafi Syarh fi al-Qira’at al-Sab’I karya 
   Abdul Fattah al-Qadhi.[/i][/color]

[color=#0000ff][size=20][b]2. Rumus dalam Ilmu Qira’at[/b][/font][/color]

    Imam asy-Syatibi adalah seorang imam yang cerdas walaupun dia tidak bisa melihat secara sempurna. Kecerdasan Imam asy-Syatibi ini dapat dibuktikan dalam bentuk karya-nya yang monomental hingga mendapatkan apresiasi dari para ulama baik yang semasa maupun setelahnya.   Dalam penulisan ilmu qira’at, sebagaimana disebutkan di atas, Imam asy-Syatibi tidak hanya melakukan inovasi baru dari bentuk natsar ke dalam bentuk syair. Tapi ia juga menggunakan kode abjad atau rumus untuk setiap imam dan perawinya. Tanda kode ini merupakan salah satu sumbangsihnya kepada generasi selanjutnya untuk memudahkan memahami dan mengidentifikasi ragam qira’at antar satu imam dengan imam yang lain. Seperti misalkan:

أبج (أ Imam Nafi’,) ( ب Warsy) dan ( ج Qalun) دهز ( دImam Ibnu Katsir) ( هـal-Bazzi) ( زQumnbul) حطي ( حImam Abu Amr) ( طal-Susi) ( يal-Duri) كلم ( كImam Ibnu Amir) ( لHisyam) ( مIbnu Dzakwan) نصع ( نImam Ashim ) ( صSyu’bah) ( عHafs) فضق ( فImam Hamzah) ( ضKhalaf) ( قKhallad) رست ( رImam Ali al-Kisa’i) ( سAbu al-Harits) ( تal-Duri)   Imam asy-Syatibi menjelaskan bahwa dia menyusun sebuah syair atau qasidah ini menggunakan tanda kode Abajadin untuk menyebutkan para imam qari’ secara berurutan. Pada huruf pertama adalah tanda kode dariapada Imam qira’at, sedangkan pada dua huruf berikutnya adalah tanda kode daripada kedua perawinya. Oleh sebab itu, Imam asy-Syatibi mengungkapkan :   وَهَا أَنَا ذَا أَسْعَى لَعَلَّ حُرُوفَهُمْ *** يَطُوعُ بِهَا نَظْمُ الْقَوَافِيْ مُسَهِّلَا جَعَلْتُ أَبَا جَادٍ عَلَى كُلِّ قَارِئٍ *** َلِيلاً عَلَى المَنْظُومِ أَوَّلَ أَوَّلا   Artinya:“ Untuk memudahkan memahami susunan dan makna nadzam ini, maka saya jadikan abajadin sebagai tanda menyebutkan para qari’ secara berurutan. Pada huruf awal ia sebagai tanda nama Imam qira’at dan huruf berikutnya adalah tanda perawinya”.   Selain itu, asy-Syatibi juga merumus-kan tanda kode gabungan para imam agar mudah diidentifikasi penyebutannya tanpa harus membuka kitab, seperti misalkan huruf tsa’ (ث) mengidentifikasi imam Kufah atau dikenal pula dengan istilah “kufiyun”; Ashim, Hamzah dan Kisa’I.   

Lihat Tabel berikut ini:

Kode   Nama Imam  Kode Nama Imam 
ث      Ashim, Hamzah dan al-Kisa’i صحبة Hamzah, Kisa’I dan Syu’bah   خ Semua imam kecuali Nafi’   صحاب Hamzah, kisa’I dan Hafs   ذ Kufiyun dan Ibnu Amir عم Nafi’ dan Ibnu Amir   ظ Kufiyun dan Ibnu Katsir سما Nafi’, Ibnu Katsir dan Abu Amr   غ Kufiyun dan Abu Amr حق Ibnu Katsir dan Abu Amr   ش Hamzah dan Kisa’i نفر Ibnu Katsir, Abu Amr dan Ibnu Amir   حرمي Nafi’ dan Ibnu Katsir حصن

    Untuk mengindentikasi ragam bacaan Imam Qira’at, seorang pengkaji cukup menghafal rumus abjad di atas. Misalkan surat al-Fatihah, imam siapa yang membaca panjang huruf mim pada lafadz (ملك) dan siapa saja yang membaca sin pada lafadz (صراط) ?   Dalam hal ini asy-Syatibi cukup mengubahnya dalam satu bait qashidah sebagai berikut:   وَمَالِكِ يَوْمِ الدِّينِ رَاوِيهِ نَاَصِرٌ *** وَعَنْدَ سِرَاطٍ وَالسِّرَاطَ لِ قُنْبُلَا بِحَيْثُ أَتَى______________   Dalam bait qashidah di atas dijelaskan bahwa yang membaca panjang huruf mim lafadz (ملك) adalah (ر) sebagai kode Imam al-Kisa’I dan (ن) sebagai kode Imam Ashim. Sementara huruf shad dalam lafadz () dibaca dengan huruf sin oleh Imam Qanbul kapanpun dijumpainya dalam ayat Al-Qur’an.   Sementara untuk mengidentifikasi rumus gabungan para ulama, dapat dijumpai dalam contoh sebagai berikut:   وَصُحْبَةُ يُصْرَفْ فَتْحُ ضَمٍّ وَرَاؤُهُ ... بِكَسْرٍ وَذَكِّرْ لَمْ يَكُنْ شَاعَ وَانْجَلَا   Bait qashidah ini menjelaskan bahwa kata (صُحْبَةُ) kode dari Imam Syu’bah, Hamzah dan al-Kisa’I membaca lafadz (يُصْرَف)-- surat al-An’am, ayat 16--,dengan fathah huruf ya’ dan kasrah huruf ra’.

    Dari beberapa pemetaan sejarah perjalanan ilmiah dan karya-karyanya di atas dapat disimpulkan bahwa Imam asy-Syatibi adalah seorang imam yang kompeten dalam berbagai disiplin ilmu utamanya dalam disiplin ilmu qira’at. Selain seorang imam dalam disiplin ilmu qira’at, asy-Syatibi merupakan seorang pendidik ulung yang mampu membangkitkan madrasah yang ia bina menjadi maju pesat hingga banyak para penuntut ilmu yang datang belajar kepadanya.   Sementara dalam karyanya ia mampu memberikan terobosan baru dalam bidang ilmu Al-Qur’an, yaitu mengubah dari bentuk natsar ke bentuk qashidah syair dan menggunakan rumusan-rumusan huruf abjad untuk mengidentifikasi para imam qira’at dan ragam bacaannya. Tujuannya adalah memudahkan para pengkaji dan penuntut ilmu qira’at generasi berikutnya.

Sumber: [color=#000088]https://nu.or.id/ilmu-al-quran/kontribusi-besar-imam-asy-syatibi-dalam-ilmu-qira-at-al-qur-an-XEith]https://nu.or.id/ilmu-al-quran/kontribusi-besar-imam-asy-syatibi-dalam-ilmu-qira-at-al-qur-an-XEith[/color].
"""