from .welcome_screen import WelcomeScreen
from .signup_screen import SignupScreen
from .reset_password_screen import ResetPasswordScreen
from .main_screen import MainScreen
from .login_screen import LoginScreen
from .mushaf_screen import MushafScreen
from .kaidah_screen import KaidahScreen
from .riwayat_screen import RiwayatScreen
from .tajewid_screen import TajewidScreen
from .donasi_screen import DonasiScreen
from .developer_screen import DeveloperScreen
#from .set_config import *